name: Build and Deploy Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Check Dockerfile presence
        run: ls -l Dockerfile

      - name: Build and push front Docker image
        run: |
          # Construire l'image front en utilisant Dockerfile à la racine
          docker build -t moncompte/monapp-front:latest -f ./Dockerfile .
          docker push moncompte/monapp-front:latest
