name: Build and Deploy Docker images

on:
  workflow_run:
    workflows: [ "Build" ] # Nom EXACT du workflow CI
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Dockerfile presence
        run: ls -l Dockerfile

      - name: Build and push front Docker image
        run: |
          docker build -t kenchisan/monapp-front:v1.0 -f ./Dockerfile .
          docker push kenchisan/monapp-front:v1.0
