name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies and run tests with coverage
        run: |
          if [ -d "front" ]; then
            cd front
          elif [ -d "front_CICD" ]; then
            cd front_CICD
          else
            echo "No frontend directory found"
            exit 1
          fi
          npm ci          npm ci
          npm run test -- --code-coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=kenchi-san_front_CICD
            -Dsonar.organization=kenchi-san-back
            -Dsonar.sources=front/src/app
            -Dsonar.tests=front/src
            -Dsonar.javascript.lcov.reportPaths=front/coverage/lcov.info
            -Dsonar.exclusions=**/*.spec.ts
